---
- name: Copy Bashrc into place
  template:
    src: "bashrc.j2"
    dest: "/home/{{ ansible_user }}/.bashrc"

- name: upgrade all packages
  apt:
    name: "*"
    state: latest
    force_apt_get: true

- name: Install common utilties
  apt:
    name: "{{ common_packages }}"
    state: latest
    force_apt_get: true

- name: Add security group for virtual machine management
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - libvirt
    - vagrant

- name: Add the user to the virtual machine management group
  user:
    name: "{{ ansible_user }}"
    append: true
    groups:
      - libvirt
      - vagrant

- name: Make sure security access directory exists
  file:
    path: /etc/polkit-1/localauthority/50-local.d/
    state: directory
    mode: 0775

- name: Copy PKLA local access authority into place
  template:
    src: libvirt-libvirt-local-access.pkla.j2
    dest: /etc/polkit-1/localauthority/50-local.d/50-org.libvirt-libvirt-local-access.pkla
    mode: 0775

- name: Increase inotify user limit
  sysctl:
    name: fs.inotify.max_user_watches
    value: 16384
    sysctl_set: yes
