---
# The download URL for the redistributable package (For Debian based Distro's - Also used for comparing versions installed vs published
gitkraken_redis_url: https://release.gitkraken.com/linux/gitkraken-amd64.deb
# Filename of GitKraken redistributable package
gitkraken_redis_filename: gitkraken-amd64.deb
