---
- hosts: localhost
  name: Provision
  gather_facts: no
  become: true
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes
  vars:
  - ansible_os_family: 'Debian'
  - ansible_architecture: 'x86_64'

  roles:
    - opsjono.package_installations
    - opsjono.gitkraken
    - opsjono.phpstorm
    - stefangweichinger.ansible-rclone
